---
- name: Capture OS flovours using environmental variables
  hosts: all
  tasks:
    - name: Display OS name
      debug:
        var: "ansible_distribution"
    - name: Display OS version
      debug:
        var: "ansible_distribution_version"
    - name: Display OS major version no
      debug:
        var: "ansible_distribution_major_version"
