---
- name: Configure tomcat
  hosts: all
  tasks:
    - name: Install tocmat10
      apt:
        name: tomcat10
        state: present
        update_cache: yes
    - name: Install tomcat10-admin
      apt:
        name: tomcat10-admin
        state: present
    - name: Copy customised tomcat-users.xml file
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat10
    - name: Change port of tomcat from 8080 to 9090
      replace:
        regexp: 8080
        replace: 9090
        path: /etc/tomcat10/server.xml
    - name: Restart tomcat
      service:
        name: tomcat10
        state: restarted
    - name: Pause for 50 seconds
      pause:
        seconds: 50
    - name: Check tomcat on server1
      uri:
        url: http://172.31.18.252:9090
        status_code: 200
    - name: Check tomcat on server2
      uri:
        url: http://172.31.19.216:9090
        status_code: 200


...
